//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SecondEntities : DbContext
    {
        public SecondEntities()
            : base("name=SecondEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
    
        public virtual ObjectResult<procGetDepartments_Result> procGetDepartments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procGetDepartments_Result>("procGetDepartments");
        }
    
        public virtual ObjectResult<procGetEmployees_Result> procGetEmployees(Nullable<int> salary)
        {
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procGetEmployees_Result>("procGetEmployees", salaryParameter);
        }
    }
}
